/**
 * Datos completos para Caso 2 (Andrea Torres) y Caso 3 (Miguel Rodríguez)
 * Este archivo complementa seed-demo-cases.ts
 */

export function getCaso2AndreaTorresDataComplete() {
  return {
    activeTab: "dashboard" as const,
    caseStatus: {
      caseNumber: "00847-2024-0-1801-JR-PE-03",
      caseType: "Penal",
      currentStage: "Juicio Oral",
      resolutionStatus: "en_tramite" as const,
      nextDeadline: {
        date: "2025-11-25",
        description: "Audiencia 4: Declaración de Andrea Torres + testigos de descargo",
      },
    },
    participants: [
      {
        id: "p1",
        name: "Andrea Sofía Torres Vega",
        role: "imputado" as const,
        contact: "+51 965 432 100",
        email: "andrea.torres@outlook.com",
        dni: "72345678",
        notes: "Diseñadora gráfica, 32 años. Imputada por estafa agravada.",
      },
      {
        id: "p2",
        name: "Dra. Valeria Montes del Río",
        role: "defensor" as const,
        contact: "+51 991 222 333",
        email: "vmontes@defensapenal.pe",
        dni: "09123456",
        notes: "Abogada defensora principal",
      },
      {
        id: "p3",
        name: "Dr. Marcos Hernández Bravo",
        role: "fiscal" as const,
        email: "mhernandez@mpfn.gob.pe",
        dni: "08234567",
        notes: "Fiscal Provincial Penal",
      },
      {
        id: "p4",
        name: "Dra. Laura Castillo Pérez",
        role: "juez" as const,
        dni: "07345678",
        notes: "Jueza del Juzgado Penal Colegiado",
      },
      {
        id: "p5",
        name: "Roberto Carlos Linares",
        role: "agraviado" as const,
        contact: "+51 987 111 222",
        dni: "45678901",
        notes: "Agraviado 1 - Empresario textil, pagó S/ 18,000",
      },
      {
        id: "p6",
        name: "Lucía Fernández Salas",
        role: "agraviado" as const,
        contact: "+51 988 333 444",
        dni: "46789012",
        notes: "Agraviada 2 - Dueña de restaurante, pagó S/ 15,000",
      },
      {
        id: "p7",
        name: "Mario Gutiérrez Rojas",
        role: "agraviado" as const,
        contact: "+51 989 555 666",
        dni: "47890123",
        notes: "Agraviado 3 - Consultor, pagó S/ 12,000",
      },
      {
        id: "p8",
        name: "Patricia Sánchez",
        role: "testigo" as const,
        contact: "+51 990 777 888",
        email: "patricia.s@designstudio.pe",
        dni: "42345678",
        notes: "Ex colega - testigo de descargo",
      },
      {
        id: "p9",
        name: "Dr. Carlos Mendoza (psicólogo)",
        role: "perito" as const,
        contact: "+51 991 888 999",
        email: "cmendoza@psi.pe",
        dni: "11234567",
        notes: "Perito psicólogo - evaluación por COVID prolongado",
      },
      {
        id: "p10",
        name: "Juan Pablo Torres",
        role: "otro" as const,
        contact: "+51 965 432 101",
        email: "jp.torres@gmail.com",
        dni: "40123456",
        notes: "Padre de Andrea - Asistente en coordinaciones",
      },
    ],
    documentFolders: [
      {
        stage: "general" as const,
        label: "Documentos Generales / Cliente",
        documents: [
          { id: "d1", filename: "DNI_Andrea_Torres.pdf", uploadDate: "2024-01-20T10:00:00Z", category: "Identificación" },
          { id: "d2", filename: "Antecedentes_Penales.pdf", uploadDate: "2024-01-20T10:05:00Z", category: "Certificados" },
          { id: "d3", filename: "Poder_Abogado.pdf", uploadDate: "2024-01-20T10:10:00Z", category: "Legal" },
          { id: "d4", filename: "Contrato_Honorarios.pdf", uploadDate: "2024-01-25T14:00:00Z", category: "Contractual" },
        ],
      },
      {
        stage: "investigacion" as const,
        label: "Investigación Preparatoria",
        documents: [
          { id: "d5", filename: "Denuncia_Fiscal_Multiple.pdf", uploadDate: "2024-01-20T09:00:00Z", category: "Denuncia" },
          { id: "d6", filename: "Declaracion_Preliminar_Andrea.pdf", uploadDate: "2024-02-10T11:00:00Z", category: "Declaraciones" },
          { id: "d7", filename: "Testimonial_Agraviado_Linares.pdf", uploadDate: "2024-02-15T10:00:00Z", category: "Testimonios" },
          { id: "d8", filename: "Testimonial_Agraviada_Fernandez.pdf", uploadDate: "2024-02-15T14:00:00Z", category: "Testimonios" },
          { id: "d9", filename: "Testimonial_Agraviado_Gutierrez.pdf", uploadDate: "2024-02-16T10:00:00Z", category: "Testimonios" },
          { id: "d10", filename: "Contratos_Servicios_Diseño.pdf", uploadDate: "2024-02-20T11:00:00Z", category: "Pruebas" },
          { id: "d11", filename: "Comprobantes_Pago_Agraviados.pdf", uploadDate: "2024-02-20T11:30:00Z", category: "Pruebas" },
          { id: "d12", filename: "Certificado_Medico_COVID_Prolongado.pdf", uploadDate: "2024-02-25T15:00:00Z", category: "Pruebas" },
          { id: "d13", filename: "Pericia_Psicologica.pdf", uploadDate: "2024-03-10T16:00:00Z", category: "Pericias" },
          { id: "d14", filename: "Disposicion_Formalizacion.pdf", uploadDate: "2024-04-15T09:00:00Z", category: "Resoluciones" },
        ],
      },
      {
        stage: "intermedia" as const,
        label: "Etapa Intermedia",
        documents: [
          { id: "d15", filename: "Requerimiento_Acusacion_Fiscal.pdf", uploadDate: "2024-08-10T09:00:00Z", category: "Acusación" },
          { id: "d16", filename: "Contestacion_Acusacion_Defensa.pdf", uploadDate: "2024-08-15T11:00:00Z", category: "Escritos Defensa" },
          { id: "d17", filename: "Ofrecimiento_Pruebas_Defensa.pdf", uploadDate: "2024-08-20T10:00:00Z", category: "Pruebas" },
          { id: "d18", filename: "Resolucion_Audiencia_Control.pdf", uploadDate: "2024-09-05T16:00:00Z", category: "Resoluciones" },
          { id: "d19", filename: "Auto_Enjuiciamiento.pdf", uploadDate: "2024-09-12T10:00:00Z", category: "Autos" },
        ],
      },
      {
        stage: "juicio_oral" as const,
        label: "Juicio Oral",
        documents: [
          { id: "d20", filename: "Acta_Audiencia_01_Instalacion.pdf", uploadDate: "2025-10-15T09:00:00Z", category: "Actas" },
          { id: "d21", filename: "Acta_Audiencia_02_Agraviados.pdf", uploadDate: "2025-10-22T09:00:00Z", category: "Actas" },
          { id: "d22", filename: "Acta_Audiencia_03_Perito_Psicologo.pdf", uploadDate: "2025-11-08T09:00:00Z", category: "Actas" },
          { id: "d23", filename: "Escrito_Solicitud_Beneficios.pdf", uploadDate: "2025-11-10T10:00:00Z", category: "Escritos Defensa" },
        ],
      },
      {
        stage: "apelacion" as const,
        label: "Apelación (2da Instancia)",
        documents: [],
      },
      {
        stage: "casacion" as const,
        label: "Casación (Corte Suprema)",
        documents: [],
      },
      {
        stage: "ejecucion" as const,
        label: "Ejecución",
        documents: [],
      },
    ],
    milestones: [
      {
        id: "m1",
        instance: "primera" as const,
        stage: "Denuncia",
        title: "Denuncias múltiples ante Fiscalía",
        date: "2024-01-20",
        description: "3 agraviados presentan denuncias por incumplimiento de servicios",
        isVerdict: false,
      },
      {
        id: "m2",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Declaración Preliminar de Andrea",
        date: "2024-02-10",
        description: "Andrea explica situación de COVID prolongado",
        isVerdict: false,
      },
      {
        id: "m3",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Evaluación Pericial Psicológica",
        date: "2024-03-10",
        description: "Perito confirma afectación psicológica por COVID",
        isVerdict: false,
      },
      {
        id: "m4",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Formalización de Investigación",
        date: "2024-04-15",
        description: "Fiscalía formaliza por delito de estafa agravada",
        isVerdict: false,
      },
      {
        id: "m5",
        instance: "primera" as const,
        stage: "Intermedia",
        title: "Acusación Fiscal",
        date: "2024-08-10",
        description: "Fiscal acusa y solicita 6 años de pena privativa",
        isVerdict: false,
      },
      {
        id: "m6",
        instance: "primera" as const,
        stage: "Intermedia",
        title: "Audiencia de Control de Acusación",
        date: "2024-09-05",
        description: "Juez admite acusación y pruebas",
        isVerdict: false,
      },
      {
        id: "m7",
        instance: "primera" as const,
        stage: "Juicio Oral",
        title: "Audiencia 1: Instalación",
        date: "2025-10-15",
        description: "Inicio del juicio oral, lectura de acusación",
        isVerdict: false,
      },
      {
        id: "m8",
        instance: "primera" as const,
        stage: "Juicio Oral",
        title: "Audiencia 2: Declaraciones de agraviados",
        date: "2025-10-22",
        description: "Los 3 agraviados declaran sobre incumplimientos",
        isVerdict: false,
      },
      {
        id: "m9",
        instance: "primera" as const,
        stage: "Juicio Oral",
        title: "Audiencia 3: Perito psicólogo",
        date: "2025-11-08",
        description: "Perito ratifica informe sobre COVID prolongado",
        isVerdict: false,
      },
      {
        id: "m10",
        instance: "primera" as const,
        stage: "Próximo",
        title: "Audiencia 4: Declaración de Andrea + testigos",
        date: "2025-11-25",
        description: "PRÓXIMA AUDIENCIA - Andrea declara + 2 testigos descargo",
        isVerdict: false,
      },
    ],
    strategy: {
      caseTheory: "Andrea Torres no actuó con ánimo de defraudar. Aceptó trabajos de buena fe pero sufrió COVID prolongado severo que le impidió cumplir. Intentó devolver dinero y renegociar, demostrando ausencia de dolo.",
      factsAnalisis: "1. Andrea contrató servicios entre nov 2023 - ene 2024\n2. COVID prolongado (certificado médico) desde feb 2024\n3. Intentos documentados de devolución parcial\n4. Correos mostrando buena fe y renegociación\n5. Evaluación psicológica confirma afectación cognitiva\n6. Sin antecedentes penales",
      objectives: [
        "Demostrar ausencia de dolo de estafa (elemento subjetivo)",
        "Probar que COVID prolongado fue causa externa imprevista",
        "Obtener absolución o pena mínima suspendida",
        "Evitar pena privativa efectiva",
      ],
      legalStrategy: "Enfatizar elemento subjetivo del dolo. COVID fue caso fortuito no previsto. Los intentos de devolución prueban buena fe. Solicitar conclusión anticipada con conformidad parcial si es necesario, buscando pena suspendida.",
      privateNotes: "Andrea es muy colaboradora y está arrepentida. La familia está apoyando económicamente. El fiscal es duro pero la jueza parece sensible al tema COVID. Estrategia: humanizar a Andrea, mostrar vulnerabilidad, ofrecer reparación civil agresiva. Conclusión anticipada es una opción realista.",
      attachments: [],
    },
    financial: {
      honorarios: 18000,
      gastos: 2800,
      reparacionCivil: 45000, // Monto solicitado por fiscal (total de lo no devuelto)
      payments: [
        {
          date: "2024-01-25",
          amount: 8000,
          concept: "Anticipo de honorarios",
        },
        {
          date: "2024-08-10",
          amount: 10000,
          concept: "Pago por acusación y juicio oral",
        },
      ],
    },
  };
}

export function getCaso3MiguelRodriguezDataComplete() {
  return {
    activeTab: "dashboard" as const,
    caseStatus: {
      caseNumber: "01245-2025-0-1801-JR-PE-07",
      caseType: "Penal",
      currentStage: "Investigación Preparatoria",
      resolutionStatus: "en_tramite" as const,
      nextDeadline: {
        date: "2025-11-25",
        description: "Resolución estimada de solicitud de Principio de Oportunidad",
      },
    },
    participants: [
      {
        id: "p1",
        name: "Pedro Martín Quispe Huamán",
        role: "otro" as const,
        contact: "+51 945 123 456",
        email: "pedro.quispe@gmail.com",
        dni: "40567890",
        notes: "Padre del imputado - Contratante de servicios legales",
      },
      {
        id: "p2",
        name: "Rosa María Huamán de Quispe",
        role: "otro" as const,
        contact: "+51 945 123 457",
        email: "rosa.huaman@gmail.com",
        dni: "41678901",
        notes: "Madre del imputado - Asistente en coordinaciones",
      },
      {
        id: "p3",
        name: "Miguel Ángel Rodríguez Paz",
        role: "imputado" as const,
        contact: "+51 945 123 458",
        email: "miguelrodriguez19@gmail.com",
        dni: "76543210",
        notes: "Imputado - 19 años, estudiante de Ingeniería Civil PUCP",
      },
      {
        id: "p4",
        name: "Dr. Alberto Rojas Luna",
        role: "defensor" as const,
        contact: "+51 992 333 444",
        email: "arojas@defensatrafico.pe",
        dni: "09234567",
        notes: "Abogado defensor especialista en delitos de tránsito",
      },
      {
        id: "p5",
        name: "Dr. Javier Prado Martínez",
        role: "fiscal" as const,
        email: "jprado@mpfn.gob.pe",
        dni: "08345678",
        notes: "Fiscal Provincial de Tránsito",
      },
      {
        id: "p6",
        name: "SO PNP Carlos Martínez",
        role: "perito" as const,
        contact: "+51 993 444 555",
        dni: "12345678",
        notes: "Perito policial - Realizó dosaje etílico",
      },
    ],
    documentFolders: [
      {
        stage: "general" as const,
        label: "Documentos Generales / Cliente",
        documents: [
          { id: "d1", filename: "DNI_Miguel_Rodriguez.pdf", uploadDate: "2025-11-10T10:00:00Z", category: "Identificación" },
          { id: "d2", filename: "DNI_Pedro_Quispe.pdf", uploadDate: "2025-11-10T10:05:00Z", category: "Identificación" },
          { id: "d3", filename: "Antecedentes_Penales_Miguel.pdf", uploadDate: "2025-11-10T10:10:00Z", category: "Certificados" },
          { id: "d4", filename: "Poder_Abogado.pdf", uploadDate: "2025-11-10T10:15:00Z", category: "Legal" },
          { id: "d5", filename: "Contrato_Honorarios.pdf", uploadDate: "2025-11-12T14:00:00Z", category: "Contractual" },
          { id: "d6", filename: "Constancia_Estudios_PUCP.pdf", uploadDate: "2025-11-12T15:00:00Z", category: "Certificados" },
        ],
      },
      {
        stage: "investigacion" as const,
        label: "Investigación Preparatoria",
        documents: [
          { id: "d7", filename: "Parte_Policial.pdf", uploadDate: "2025-11-05T23:30:00Z", category: "Denuncia" },
          { id: "d8", filename: "Protocolo_Dosaje_Etilico.pdf", uploadDate: "2025-11-05T23:45:00Z", category: "Pericias" },
          { id: "d9", filename: "Acta_Constatacion_Accidente.pdf", uploadDate: "2025-11-06T00:15:00Z", category: "Pruebas" },
          { id: "d10", filename: "Fotos_Lugar_Accidente.pdf", uploadDate: "2025-11-06T08:00:00Z", category: "Pruebas" },
          { id: "d11", filename: "Informe_Pericia_Vehicular.pdf", uploadDate: "2025-11-07T14:00:00Z", category: "Pericias" },
          { id: "d12", filename: "Declaracion_Preliminar_Miguel.pdf", uploadDate: "2025-11-12T11:00:00Z", category: "Declaraciones" },
          { id: "d13", filename: "Disposicion_Formalizacion.pdf", uploadDate: "2025-11-15T09:00:00Z", category: "Resoluciones" },
          { id: "d14", filename: "Solicitud_Principio_Oportunidad.pdf", uploadDate: "2025-11-17T10:00:00Z", category: "Escritos Defensa" },
        ],
      },
      {
        stage: "intermedia" as const,
        label: "Etapa Intermedia",
        documents: [],
      },
      {
        stage: "juicio_oral" as const,
        label: "Juicio Oral",
        documents: [],
      },
      {
        stage: "apelacion" as const,
        label: "Apelación (2da Instancia)",
        documents: [],
      },
      {
        stage: "casacion" as const,
        label: "Casación (Corte Suprema)",
        documents: [],
      },
      {
        stage: "ejecucion" as const,
        label: "Ejecución",
        documents: [],
      },
    ],
    milestones: [
      {
        id: "m1",
        instance: "primera" as const,
        stage: "Flagrancia",
        title: "Intervención Policial",
        date: "2025-11-05",
        description: "Miguel intervenido por PNP tras impactar contra poste",
        isVerdict: false,
      },
      {
        id: "m2",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Dosaje Etílico Positivo",
        date: "2025-11-05",
        description: "Resultado: 0.8 g/l de alcohol en sangre",
        isVerdict: false,
      },
      {
        id: "m3",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Contratación de Defensa",
        date: "2025-11-10",
        description: "Padres contratan al Dr. Alberto Rojas",
        isVerdict: false,
      },
      {
        id: "m4",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Declaración Preliminar",
        date: "2025-11-12",
        description: "Miguel admite hechos y expresa arrepentimiento",
        isVerdict: false,
      },
      {
        id: "m5",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Formalización de Investigación",
        date: "2025-11-15",
        description: "Fiscal formaliza por Art. 274 CP (conducción en ebriedad)",
        isVerdict: false,
      },
      {
        id: "m6",
        instance: "primera" as const,
        stage: "Investigación",
        title: "Solicitud de Principio de Oportunidad",
        date: "2025-11-17",
        description: "Defensa solicita PO: sin antecedentes, menor gravedad, estudiante",
        isVerdict: false,
      },
      {
        id: "m7",
        instance: "primera" as const,
        stage: "Próximo",
        title: "Resolución de Principio de Oportunidad",
        date: "2025-11-25",
        description: "PENDIENTE - Se espera respuesta de Fiscalía sobre PO",
        isVerdict: false,
      },
    ],
    strategy: {
      caseTheory: "Miguel cometió un error propio de su juventud sin generar daños a terceros. Procede Principio de Oportunidad por: delito de menor gravedad (Art. 274 CP, pena < 4 años), sin antecedentes, sin víctimas, sin daños materiales a terceros, estudiante universitario con futuro promisorio.",
      factsAnalisis: "1. Hecho flagrante: dosaje 0.8 g/l\n2. Solo daños al poste municipal (reparables)\n3. Sin víctimas humanas\n4. Sin antecedentes penales ni policiales\n5. Estudiante de ingeniería con buen rendimiento\n6. Familia presente y comprometida\n7. Reconocimiento de hechos y arrepentimiento",
      objectives: [
        "Obtener Principio de Oportunidad (evitar juicio)",
        "Pagar reparación civil al municipio (S/ 5,000)",
        "Evitar antecedentes penales para Miguel",
        "Preservar futuro académico y profesional",
      ],
      legalStrategy: "Solicitar PO de inmediato basado en Art. 2 CPP. Enfatizar: menor gravedad, sin víctimas, sin antecedentes, estudiante. Ofrecer reparación civil inmediata de S/ 5,000 al municipio. Si Fiscalía rechaza, considerar acuerdo reparatorio o conclusión anticipada con pena suspendida.",
      privateNotes: "Miguel está MUY arrepentido. Los padres son personas trabajadoras y responsables. Este es claramente un caso para PO. El fiscal Prado suele ser razonable con jóvenes sin antecedentes. Estrategia: mover rápido el PO antes que se complique. Reparación civil de S/ 5,000 es más que suficiente (poste cuesta S/ 3,000).",
      attachments: [],
    },
    financial: {
      honorarios: 8000,
      gastos: 800,
      reparacionCivil: 5000, // A favor del municipio
      payments: [
        {
          date: "2025-11-12",
          amount: 5000,
          concept: "Anticipo de honorarios",
        },
      ],
    },
  };
}
